### ISSUE TITLE
交流

### ISSUE THREAD

**Issue by yatogami-12** [stavhaygn/crack-tixcraft#1]
你好我上次aimer的時候也寫過一個只是在提交完要配票的時候都是一直check然後到最後就沒票了，請問你有遇過類似狀況嗎，不過這都只發生在開賣的時候，不是開賣期間就沒問題了

**Comment by stavhaygn** [comment]
你好，
我也有遇過類似的問題，發生在/ticket/order與/ticket/check，不斷的等待5秒，之後又被退回到/ticket/ticket，重新輸入驗證碼與選擇票數，同樣是在熱門活動開賣時發生，不知道是否遇你遇到的相同？

另外，熱門活動開賣時，/ticket/area有機會顯示無座位，但重整後又有座位，不管是用程式或人工購票都有相同的問題。

以上兩個問題，我個人認為是官方伺服器所造成的，若你有其他想法或疑問，歡迎你與我分享。

**Comment by yatogami-12** [comment]
應該是一樣的，check我認為他可能在配票的時候基於某些規則會做某些阻擋，因為我上禮拜有試過連五百開賣當下沒賣完都出現這種狀況
area顯示無座位我認為是伺服器問題
