### ISSUE TITLE
請求

### ISSUE THREAD

**Issue by mikekuanhsuan** [stavhaygn/crack-tixcraft#20]
您好
打擾了
驗證碼字體有黏在一起的問題,是如何訓練？
方便跟你們拿取model?

**Comment by stavhaygn** [comment]
@mikekuanhsuan 你好，
我們是實踐這 repo https://github.com/JasonLiTW/simple-railway-captcha-solver 的想法來產生資料集與模型架構，
但當初並無處理字體相黏以及其他潛在問題，
因此僅有對於 Reenie_Beanie 字型之模型辨識正確率較高，
至於模型之其他需求，請私下聯繫，謝謝

**Comment by mikekuanhsuan** [comment]
> @mikekuanhsuan 你好，
> 我們是實踐這 repo https://github.com/JasonLiTW/simple-railway-captcha-solver 的想法來產生資料集與模型架構，
> 但當初並無處理字體相黏以及其他潛在問題，
> 因此僅有對於 Reenie_Beanie 字型之模型辨識正確率較高，
> 至於模型之其他需求，請私下聯繫，謝謝

kuanhsuankao@gmail.com
這是我的mail
如果方便提供google drive 非常感謝🙏

**Comment by stavhaygn** [comment]
@mikekuanhsuan 好的
