### ISSUE TITLE
關於.h5檔案問題

### ISSUE THREAD

**Issue by howardwch1951** [stavhaygn/crack-tixcraft#25]
請問 @stavhaygn 大大
models資料夾內是否少了Font_model.h5和Reenie_Beanie_model.h5這兩個檔案呢?
因為在load_model讀這兩個檔案時
回傳都會是空值
![image](https://user-images.githubusercontent.com/76759199/182117181-691086da-36b2-4ad7-8908-38e857209240.png)

**Comment by stavhaygn** [comment]
@howardwch1951 您好：

本專案不提供 Font_model.h5 與 Reenie_Beanie_model.h5 模型，
其它部分已於信件中討論。
